export const SOURCE_META = [
  { id: "anthropic-news", displayName: "Anthropic News", category: "claude", tier: 1 },
  { id: "anthropic-engineering", displayName: "Anthropic Engineering", category: "claude", tier: 1 },
  { id: "openai-news", displayName: "OpenAI News", category: "codex", tier: 1 },
  { id: "openai-blog", displayName: "OpenAI Blog", category: "codex", tier: 1 },
  { id: "google-deepmind", displayName: "Google DeepMind Blog", category: "gemini", tier: 1 },
  { id: "google-developers", displayName: "Google Developers Blog", category: "gemini", tier: 1 },
  { id: "github-blog-ai", displayName: "GitHub Blog (AI & ML)", category: "copilot", tier: 1 },
  { id: "github-copilot", displayName: "GitHub Copilot Blog", category: "copilot", tier: 1 },
  { id: "microsoft-foundry", displayName: "Microsoft Foundry Blog", category: "copilot", tier: 1 },
  { id: "google-cloud-blog", displayName: "Google Cloud Blog", category: "gemini", tier: 1 },
  { id: "aws-ml-blog", displayName: "AWS Machine Learning Blog", category: "agent-fw", tier: 1 },
  { id: "meta-engineering", displayName: "Meta Engineering", category: "tech-news", tier: 1 },
  { id: "netflix-techblog", displayName: "Netflix TechBlog", category: "tech-news", tier: 1 },
  { id: "github-changelog", displayName: "GitHub Changelog", category: "copilot", tier: 1 },
  { id: "huggingface-blog", displayName: "Hugging Face Blog", category: "local-llm", tier: 1 },
  { id: "ollama-releases", displayName: "Ollama Releases", category: "local-llm", tier: 1 },
  { id: "arxiv-cs-cl", displayName: "arXiv cs.CL", category: "research", tier: 1 },
  { id: "arxiv-cs-se", displayName: "arXiv cs.SE", category: "research", tier: 1 },
  { id: "zenn-ai", displayName: "Zenn AI tag", category: "local-llm", tier: 1 },
  { id: "qiita-copilot", displayName: "Qiita GitHub Copilot tag", category: "copilot", tier: 1 },
  { id: "zenn-llm", displayName: "Zenn LLM tag", category: "local-llm", tier: 2 },
  { id: "zenn-claude", displayName: "Zenn Claude tag", category: "claude", tier: 2 },
  { id: "zenn-copilot", displayName: "Zenn GitHub Copilot tag", category: "copilot", tier: 2 },
  { id: "zenn-mcp", displayName: "Zenn MCP tag", category: "mcp", tier: 2 },
  { id: "zenn-cursor", displayName: "Zenn Cursor tag", category: "cursor", tier: 2 },
  { id: "qiita-claude", displayName: "Qiita Claude tag", category: "claude", tier: 2 },
  { id: "qiita-llm", displayName: "Qiita LLM tag", category: "local-llm", tier: 2 },
  { id: "qiita-mcp", displayName: "Qiita MCP tag", category: "mcp", tier: 2 },
  { id: "qiita-vscode", displayName: "Qiita VSCode tag", category: "vscode", tier: 2 },
  { id: "qiita-cursor", displayName: "Qiita Cursor tag", category: "cursor", tier: 2 },
  { id: "vscode-updates", displayName: "VS Code Updates", category: "vscode", tier: 1 },
  { id: "simonw-blog", displayName: "Simon Willison's Weblog", category: "local-llm", tier: 2 },
  { id: "aider-releases", displayName: "Aider Releases", category: "aider", tier: 2 },
  { id: "cline-releases", displayName: "Cline Releases", category: "cline", tier: 2 },
  { id: "continue-releases", displayName: "Continue.dev Releases", category: "copilot", tier: 2 },
  { id: "openhands-releases", displayName: "OpenHands Releases", category: "opencode", tier: 2 },
  { id: "zed-releases", displayName: "Zed Editor Releases", category: "cursor", tier: 2 },
  { id: "autogen-releases", displayName: "Microsoft AutoGen Releases", category: "agent-fw", tier: 2 },
  { id: "langchain-releases", displayName: "LangChain Releases", category: "agent-fw", tier: 2 },
  { id: "semantic-kernel-releases", displayName: "Semantic Kernel Releases", category: "agent-fw", tier: 2 },
  { id: "mcp-servers-releases", displayName: "MCP Servers Releases", category: "mcp", tier: 2 },
  { id: "cursor-changelog", displayName: "Cursor Changelog", category: "cursor", tier: 2 },
  { id: "arxiv-cs-ai", displayName: "arXiv cs.AI", category: "research", tier: 2 },
  { id: "arxiv-cs-lg", displayName: "arXiv cs.LG", category: "research", tier: 2 },
  { id: "apple-newsroom", displayName: "Apple Newsroom", category: "tech-news", tier: 2 },
  { id: "microsoft-source", displayName: "Microsoft Source", category: "tech-news", tier: 2 },
  { id: "google-keyword", displayName: "Google Keyword Blog", category: "tech-news", tier: 2 },
  { id: "meta-newsroom", displayName: "Meta Newsroom", category: "tech-news", tier: 2 },
  { id: "aws-news", displayName: "AWS News Blog", category: "tech-news", tier: 2 },
  { id: "nvidia-blog", displayName: "NVIDIA Blog", category: "tech-news", tier: 2 },
  { id: "techcrunch", displayName: "TechCrunch", category: "tech-news", tier: 2 },
  { id: "the-verge", displayName: "The Verge", category: "tech-news", tier: 2 },
  { id: "ars-technica", displayName: "Ars Technica", category: "tech-news", tier: 2 },
  { id: "dora-insights", displayName: "DORA Insights (Google)", category: "research", tier: 2 },
  { id: "hn-ai", displayName: "Hacker News - AI coding", category: "research", tier: 3 },
  { id: "user-opml", displayName: "User OPML (custom feeds)", category: "research", tier: 3 },
  { id: "youtube-anthropic", displayName: "YouTube - Anthropic", category: "claude", tier: 3 },
] as const;
