/**
 * Per-URL body cache (KV) helpers — body-file architecture, Phase B (LL-115).
 *
 * Long-form article bodies are generated by the dedicated `worker-body` Queue
 * consumer (opus-4.8) and written here, one KV key per URL. The collector
 * Worker reads these and merges them into `data/bodies.json` on publish.
 *
 * Mirrors kv-cache.ts (summary cache) but with a `b:` key prefix so bodies and
 * summaries never collide in the SAME KV namespace (SUMMARY_CACHE). Reusing the
 * namespace avoids provisioning a second one; the prefix scopes the two key
 * spaces (`s:` summaries, `b:` bodies, OG image cache uses its own keys).
 *
 * Key format: `b:{hex-sha256(url)}` — stable across Workers (subtle.digest) and
 * Node (crypto.subtle), 66 chars, well under KV's 512-byte key limit.
 */
export interface BodyCacheEntry {
  bodyJa: string;
  bodyEn: string;
  model: string;
  cachedAt: string;
}

const KEY_PREFIX = "b:";

function toHex(buf: ArrayBuffer): string {
  const bytes = new Uint8Array(buf);
  let out = "";
  for (let i = 0; i < bytes.length; i++) {
    out += bytes[i]!.toString(16).padStart(2, "0");
  }
  return out;
}

/** SHA-256 hex digest of the URL with the `b:` body prefix. */
export async function bodyCacheKeyForUrl(url: string): Promise<string> {
  const data = new TextEncoder().encode(url);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return KEY_PREFIX + toHex(digest);
}

/** Read a single body cache entry by URL. Returns null on miss or parse error. */
export async function getBodyCacheEntry(
  kv: KVNamespace,
  url: string,
): Promise<BodyCacheEntry | null> {
  const key = await bodyCacheKeyForUrl(url);
  return (await kv.get<BodyCacheEntry>(key, "json")) ?? null;
}

/**
 * Read N body cache entries in parallel. Returns a Map<url, BodyCacheEntry>;
 * missing URLs are simply absent. Each KV.get is one subrequest, so callers
 * must cap the number of URLs per invocation (BODY_LOOKUP_CAP).
 */
export async function getBodyCacheEntries(
  kv: KVNamespace,
  urls: readonly string[],
): Promise<Map<string, BodyCacheEntry>> {
  const out = new Map<string, BodyCacheEntry>();
  if (urls.length === 0) return out;
  const keys = await Promise.all(urls.map(bodyCacheKeyForUrl));
  const values = await Promise.all(keys.map((k) => kv.get<BodyCacheEntry>(k, "json")));
  for (let i = 0; i < urls.length; i++) {
    const v = values[i];
    if (v) out.set(urls[i]!, v);
  }
  return out;
}

/** Write a single body cache entry by URL. One KV.put (LL-043 write-budget). */
export async function putBodyCacheEntry(
  kv: KVNamespace,
  url: string,
  entry: BodyCacheEntry,
): Promise<void> {
  const key = await bodyCacheKeyForUrl(url);
  await kv.put(key, JSON.stringify(entry));
}

/** True when a body cache entry has real, renderable bilingual prose. */
export function isBodyComplete(entry: BodyCacheEntry | null | undefined): boolean {
  return Boolean(entry && entry.bodyJa.trim() && entry.bodyEn.trim());
}
