/**
 * Source registry — maps SourceId → SourceDefinition.
 *
 * Phase 1: 6 initial RSS/Atom sources covering 4 categories.
 * Phase 2+ will grow this to the full Tier 2 (30 sources) per site-spec §1.4.
 */
import type { SourceDefinition } from "./types.ts";
import { collectRss } from "./collectors/rss.ts";
import { collectVscodeUpdates } from "./collectors/vscode-updates.ts";
import {
  collectAnthropicNews,
  collectAnthropicEngineering,
} from "./collectors/anthropic.ts";
import { collectHnAlgolia } from "./collectors/hn-algolia.ts";
import { collectOpml } from "./collectors/opml.ts";
import { youtubeChannel } from "./collectors/youtube.ts";

export const REGISTRY: Readonly<Record<string, SourceDefinition>> = Object.freeze({
  "anthropic-news": {
    id: "anthropic-news",
    displayName: "Anthropic News",
    category: "claude",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["anthropic", "claude"],
    feedUrl: "https://www.anthropic.com/news",
    tier: 1,
    collect: collectAnthropicNews,
  },
  "anthropic-engineering": {
    id: "anthropic-engineering",
    displayName: "Anthropic Engineering",
    category: "claude",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["anthropic", "engineering"],
    feedUrl: "https://www.anthropic.com/engineering",
    tier: 1,
    collect: collectAnthropicEngineering,
  },

  "openai-news": {
    id: "openai-news",
    displayName: "OpenAI News",
    category: "codex",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["openai"],
    feedUrl: "https://openai.com/news/rss.xml",
    tier: 1,
    collect: collectRss,
  },
  "openai-blog": {
    id: "openai-blog",
    displayName: "OpenAI Blog",
    category: "codex",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["openai"],
    feedUrl: "https://openai.com/blog/rss.xml",
    tier: 1,
    collect: collectRss,
  },
  "google-deepmind": {
    id: "google-deepmind",
    displayName: "Google DeepMind Blog",
    category: "gemini",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["google", "deepmind"],
    feedUrl: "https://deepmind.google/blog/rss.xml",
    tier: 1,
    collect: collectRss,
  },
  "google-developers": {
    id: "google-developers",
    displayName: "Google Developers Blog",
    category: "gemini",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["google"],
    feedUrl: "https://developers.googleblog.com/feeds/posts/default",
    tier: 1,
    collect: collectRss,
  },
  "github-blog-ai": {
    id: "github-blog-ai",
    displayName: "GitHub Blog (AI & ML)",
    category: "copilot",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["github"],
    feedUrl: "https://github.blog/category/ai-and-ml/feed/",
    tier: 1,
    collect: collectRss,
  },
  "github-changelog": {
    id: "github-changelog",
    displayName: "GitHub Changelog",
    category: "copilot",
    sourceType: "changelog",
    defaultLang: "en",
    autoTags: ["github", "changelog"],
    feedUrl: "https://github.blog/changelog/feed/",
    tier: 1,
    collect: collectRss,
  },
  "huggingface-blog": {
    id: "huggingface-blog",
    displayName: "Hugging Face Blog",
    category: "local-llm",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["huggingface", "open-model"],
    feedUrl: "https://huggingface.co/blog/feed.xml",
    tier: 1,
    collect: collectRss,
  },
  "ollama-releases": {
    id: "ollama-releases",
    displayName: "Ollama Releases",
    category: "local-llm",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["ollama", "release"],
    feedUrl: "https://github.com/ollama/ollama/releases.atom",
    tier: 1,
    collect: collectRss,
  },
  "arxiv-cs-cl": {
    id: "arxiv-cs-cl",
    displayName: "arXiv cs.CL",
    category: "research",
    sourceType: "paper",
    defaultLang: "en",
    autoTags: ["arxiv", "paper"],
    feedUrl: "https://rss.arxiv.org/rss/cs.CL",
    tier: 1,
    collect: collectRss,
  },
  "arxiv-cs-se": {
    id: "arxiv-cs-se",
    displayName: "arXiv cs.SE",
    category: "research",
    sourceType: "paper",
    defaultLang: "en",
    autoTags: ["arxiv", "paper"],
    feedUrl: "https://rss.arxiv.org/rss/cs.SE",
    tier: 1,
    collect: collectRss,
  },
  "zenn-ai": {
    id: "zenn-ai",
    displayName: "Zenn AI tag",
    category: "research",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["zenn"],
    feedUrl: "https://zenn.dev/topics/ai/feed",
    tier: 1,
    collect: collectRss,
  },
  "qiita-copilot": {
    id: "qiita-copilot",
    displayName: "Qiita GitHub Copilot tag",
    category: "copilot",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["qiita"],
    feedUrl: "https://qiita.com/tags/githubcopilot/feed.atom",
    tier: 1,
    collect: collectRss,
  },
  "vscode-updates": {
    id: "vscode-updates",
    displayName: "VS Code Updates",
    category: "vscode",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["vscode", "release"],
    feedUrl: "https://code.visualstudio.com/updates",
    tier: 1,
    collect: collectVscodeUpdates,
  },
  "simonw-blog": {
    id: "simonw-blog",
    displayName: "Simon Willison's Weblog",
    category: "research",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["newsletter"],
    feedUrl: "https://simonwillison.net/atom/everything/",
    tier: 2,
    collect: collectRss,
  },

  // ============ Tier 2 ============
  "aider-releases": {
    id: "aider-releases",
    displayName: "Aider Releases",
    category: "aider",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["aider", "release"],
    feedUrl: "https://github.com/Aider-AI/aider/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "cline-releases": {
    id: "cline-releases",
    displayName: "Cline Releases",
    category: "cline",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["cline", "release"],
    feedUrl: "https://github.com/cline/cline/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "continue-releases": {
    id: "continue-releases",
    displayName: "Continue.dev Releases",
    category: "copilot",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["continue", "release"],
    feedUrl: "https://github.com/continuedev/continue/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "openhands-releases": {
    id: "openhands-releases",
    displayName: "OpenHands Releases",
    category: "opencode",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["openhands", "release"],
    feedUrl: "https://github.com/All-Hands-AI/OpenHands/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "zed-releases": {
    id: "zed-releases",
    displayName: "Zed Editor Releases",
    category: "vscode",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["zed", "editor", "release"],
    feedUrl: "https://github.com/zed-industries/zed/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "autogen-releases": {
    id: "autogen-releases",
    displayName: "Microsoft AutoGen Releases",
    category: "agent-fw",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["autogen", "agent", "release"],
    feedUrl: "https://github.com/microsoft/autogen/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "langchain-releases": {
    id: "langchain-releases",
    displayName: "LangChain Releases",
    category: "agent-fw",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["langchain", "agent", "release"],
    feedUrl: "https://github.com/langchain-ai/langchain/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "semantic-kernel-releases": {
    id: "semantic-kernel-releases",
    displayName: "Semantic Kernel Releases",
    category: "agent-fw",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["semantic-kernel", "agent", "release"],
    feedUrl: "https://github.com/microsoft/semantic-kernel/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "mcp-servers-releases": {
    id: "mcp-servers-releases",
    displayName: "MCP Servers Releases",
    category: "mcp",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["mcp", "release"],
    feedUrl: "https://github.com/modelcontextprotocol/servers/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "cursor-changelog": {
    id: "cursor-changelog",
    displayName: "Cursor Changelog",
    category: "cursor",
    sourceType: "changelog",
    defaultLang: "en",
    autoTags: ["cursor", "changelog"],
    feedUrl: "https://www.cursor.com/changelog/rss.xml",
    tier: 2,
    collect: collectRss,
  },
  "arxiv-cs-ai": {
    id: "arxiv-cs-ai",
    displayName: "arXiv cs.AI",
    category: "research",
    sourceType: "paper",
    defaultLang: "en",
    autoTags: ["arxiv", "paper"],
    feedUrl: "https://rss.arxiv.org/rss/cs.AI",
    tier: 2,
    collect: collectRss,
  },
  "arxiv-cs-lg": {
    id: "arxiv-cs-lg",
    displayName: "arXiv cs.LG",
    category: "research",
    sourceType: "paper",
    defaultLang: "en",
    autoTags: ["arxiv", "paper"],
    feedUrl: "https://rss.arxiv.org/rss/cs.LG",
    tier: 2,
    collect: collectRss,
  },

  // ============ Tech News (Tier 2) ============
  "apple-newsroom": {
    id: "apple-newsroom",
    displayName: "Apple Newsroom",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["apple", "news"],
    feedUrl: "https://www.apple.com/newsroom/rss-feed.rss",
    tier: 2,
    collect: collectRss,
  },
  "microsoft-source": {
    id: "microsoft-source",
    displayName: "Microsoft Source",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["microsoft", "news"],
    feedUrl: "https://news.microsoft.com/source/feed/",
    tier: 2,
    collect: collectRss,
  },
  "google-keyword": {
    id: "google-keyword",
    displayName: "Google Keyword Blog",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["google", "news"],
    feedUrl: "https://blog.google/rss/",
    tier: 2,
    collect: collectRss,
  },
  "meta-newsroom": {
    id: "meta-newsroom",
    displayName: "Meta Newsroom",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["meta", "news"],
    feedUrl: "https://about.fb.com/news/feed/",
    tier: 2,
    collect: collectRss,
  },
  "aws-news": {
    id: "aws-news",
    displayName: "AWS News Blog",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["aws", "amazon", "news"],
    feedUrl: "https://aws.amazon.com/blogs/aws/feed/",
    tier: 2,
    collect: collectRss,
  },
  "nvidia-blog": {
    id: "nvidia-blog",
    displayName: "NVIDIA Blog",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["nvidia", "news"],
    feedUrl: "https://blogs.nvidia.com/feed/",
    tier: 2,
    collect: collectRss,
  },
  "techcrunch": {
    id: "techcrunch",
    displayName: "TechCrunch",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["techcrunch", "news"],
    feedUrl: "https://techcrunch.com/feed/",
    tier: 2,
    collect: collectRss,
  },
  "the-verge": {
    id: "the-verge",
    displayName: "The Verge",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["verge", "news"],
    feedUrl: "https://www.theverge.com/rss/index.xml",
    tier: 2,
    collect: collectRss,
  },
  "ars-technica": {
    id: "ars-technica",
    displayName: "Ars Technica",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["ars-technica", "news"],
    feedUrl: "https://arstechnica.com/feed/",
    tier: 2,
    collect: collectRss,
  },
  // ============ Tier 3 ============
  "hn-ai": {
    id: "hn-ai",
    displayName: "Hacker News — AI coding",
    category: "research",
    sourceType: "community",
    defaultLang: "en",
    autoTags: ["hackernews", "community"],
    feedUrl:
      "https://hn.algolia.com/api/v1/search?query=%22AI+coding%22+OR+%22LLM%22+OR+%22MCP%22&tags=story&hitsPerPage=30",
    tier: 3,
    collect: collectHnAlgolia,
  },
  "user-opml": {
    id: "user-opml",
    displayName: "User OPML (custom feeds)",
    category: "research",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["user"],
    feedUrl: "file://data/user-opml.xml",
    tier: 3,
    collect: collectOpml,
  },
  // Example YouTube channel — Anthropic. Users can copy this pattern.
  "youtube-anthropic": {
    ...youtubeChannel(
      "youtube-anthropic",
      "YouTube — Anthropic",
      "UCrDwWp7EBBv4NwvScIpBDOA",
      ["anthropic"],
    ),
    category: "claude",
  },
});

export function listSources(): SourceDefinition[] {
  return Object.values(REGISTRY);
}
