/**
 * Source registry - maps SourceId to SourceDefinition.
 *
 * Current production registry covers 50 sources across 14 categories.
 * Keep web/src/lib/source-meta.ts in sync so the Pages build stays self-contained.
 */
import type { SourceDefinition } from "./types.ts";
import { collectRss } from "./collectors/rss.ts";
import { collectVscodeUpdates } from "./collectors/vscode-updates.ts";
import {
  collectAnthropicNews,
  collectAnthropicEngineering,
} from "./collectors/anthropic.ts";
import { collectHnAlgolia } from "./collectors/hn-algolia.ts";
import { collectOpml } from "./collectors/opml.ts";
import { youtubeChannel } from "./collectors/youtube.ts";

const RESEARCH_RELEVANCE_KEYWORDS = [
  "llm",
  "large language model",
  "language model",
  "foundation model",
  "code generation",
  "software engineering",
  "program repair",
  "program synthesis",
  "swe-bench",
  "swebench",
  "repository",
  "github",
  "coding",
  "developer",
  "agent",
  "agents",
  "agentic",
  "tool use",
  "mcp",
  "retrieval-augmented",
  "rag",
  "prompt",
  "reasoning",
] as const;

const RESEARCH_EXCLUDE_KEYWORDS = [
  "autonomous driving",
  "flooded road",
  "medical",
  "biological",
  "protein",
  "molecule",
  "genome",
  "text-to-image",
  "vision-language",
  "segmentation",
  "robot",
  "robotics",
  "clinical code prediction",
] as const;

const DORA_EXCLUDE_KEYWORDS = [
  "devops dozen awards",
  "quick check updates",
] as const;

const AWS_ML_RELEVANCE_KEYWORDS = [
  "artificial intelligence",
  "ai",
  "machine learning",
  "ml",
  "agent",
  "agentic",
  "agentcore",
  "mcp",
  "model",
  "bedrock",
  "sagemaker",
  "nova",
  "claude",
  "rag",
  "llm",
  "inference",
  "reinforcement learning",
  "computer vision",
  "vision",
  "language model",
  "deep learning",
  "neural",
  "foundation model",
  "text extraction",
  "redacting",
  "pipeline",
  "frontier",
] as const;

const AWS_ML_EXCLUDE_KEYWORDS = [
  // Amazon Quick / QuickSight is included in the ML feed even when the article
  // is a generic BI feature or backup operation with no agent/ML engineering.
  "mobile layout for amazon quick",
  "backup strategy for amazon quick sight",
] as const;

const TECH_NEWS_RELEVANCE_KEYWORDS = [
  "artificial intelligence",
  "ai",
  "image generation",
  "text generation",
  "text-to-image",
  "developer",
  "developers",
  "software engineering",
  "coding",
  "development",
  "developer tool",
  "developer tools",
  "framework",
  "frameworks",
  "open source",
  "cloud",
  "infrastructure",
  "api",
  "sdk",
  "github",
  "copilot",
  "openai",
  "chatgpt",
  "anthropic",
  "claude",
  "gemini",
  "gemma",
  "midjourney",
  "llm",
  "model",
  "models",
  "agent",
  "agentic",
  "mcp",
  "prompt injection",
  "gpu",
  "nvidia",
  "chip",
  "chips",
  "graviton",
  "bedrock",
  "inference",
  "security",
  "privacy",
  "backdoor",
  "backdoored",
  "malware",
  "breach",
  "hackers",
  "phishing",
  "exploit",
  "credential stealer",
  "password vault",
  "vulnerability",
  "0-day",
  "zero-day",
  "jailbreak",
  "guardrails",
  "tech debt",
  "s3",
  "interconnect",
  "ecs",
  "aurora postgresql",
] as const;

const TECH_NEWS_EXCLUDE_KEYWORDS = [
  "deal",
  "sale",
  "memorial day",
  "airfly",
  "govee",
  "lamp",
  "water bottle",
  "camera assistant",
  "spacex",
  "starship",
  "rocket",
  "blue origin",
  "dead pilots",
  "gadget",
  "summer travel",
  "tv",
  "streaming",
  "playstation",
  "xbox",
  "neo geo",
  "dating service",
  "dating app",
  "side hustle",
  "critique your photos",
  "indie game developer",
  "fortnite",
  "destiny",
  "gta",
  "minecraft",
  "god of war",
  "witcher",
  "trails",
  "hiking",
  "bee wearable",
  "esports",
  "beluga",
  "shuttle",
  "astronaut",
  "seafood",
  "ebola",
  "chromecast",
  "mandalorian",
  "the boys",
  "superfans",
  "solar",
  "vpn where criminals",
  "satellite",
  "space station",
  "space development agency",
  "the view",
  "shark finning",
  "study notebooks",
  "coffee shop",
  "small business growth academy",
  "iste 2026",
  "local currency pricing",
  "educators and industry leaders",
  "education and ai",
  "universities are preparing students",
  "digital literacy",
  "ai literacy",
  "imagine cup",
  "weekly roundup",
  "startup forum",
  "geforce now",
  "g cloud",
  "games hit the cloud",
  "vehicle outlives its cloud",
  "killing your spouse",
] as const;

const HN_AI_RELEVANCE_KEYWORDS = [
  "show hn",
  "ai",
  "llm",
  "agentic",
  "mcp",
  "agent",
  "agents",
  "coding",
  "developer",
  "developer tool",
  "dev tool",
  "open source",
  "cli",
  "api",
  "copilot",
  "claude",
  "openai",
  "gemini",
  "cursor",
  "vscode",
] as const;

const HN_AI_EXCLUDE_KEYWORDS = [
  "who is hiring",
  "hiring",
  "job board",
  "freelance",
  "consulting",
] as const;

const LOCAL_LLM_RELEVANCE_KEYWORDS = [
  "local llm",
  "local model",
  "on-device",
  "open model",
  "open-source model",
  "open weights",
  "ollama",
  "llama",
  "llama.cpp",
  "gguf",
  "quantization",
  "quantized",
  "vllm",
  "lm studio",
  "mlx",
  "hugging face",
  "transformers",
  "deepseek",
  "qwen",
  "gemma",
  "mistral",
  "llm-jp",
  "\u30ed\u30fc\u30ab\u30eb",
  "\u91cf\u5b50\u5316",
] as const;

// The broad Zenn AI tag needs a topic signal, not a generic local-PC/filesystem mention.
const ZENN_AI_LOCAL_LLM_RELEVANCE_KEYWORDS = [
  ...LOCAL_LLM_RELEVANCE_KEYWORDS.filter((keyword) => keyword !== "\u30ed\u30fc\u30ab\u30eb"),
  "\u30ed\u30fc\u30ab\u30ebllm",
  "\u30ed\u30fc\u30ab\u30eb llm",
  "\u30ed\u30fc\u30ab\u30ebai",
  "\u30ed\u30fc\u30ab\u30eb ai",
  "\u30ed\u30fc\u30ab\u30eb\u8a00\u8a9e\u30e2\u30c7\u30eb",
  "\u30ed\u30fc\u30ab\u30eb\u30e2\u30c7\u30eb",
  "\u30ed\u30fc\u30ab\u30eb \u30e2\u30c7\u30eb",
  "\u30aa\u30f3\u30c7\u30d0\u30a4\u30b9",
  "diffusiongemma",
  "llm",
  "slm",
  "vram",
] as const;

const LOCAL_LLM_EXCLUDE_KEYWORDS = [
  "saas is dead",
  "profit",
  "profitable",
  "sales",
  "startup",
  "invoice",
  "billing accident",
  "\u55b6\u696d",
  "\u9ed2\u5b57",
  "\u53ce\u76ca",
  "\u8acb\u6c42",
  "claude code",
  "mcp",
  "workflow",
  "agent",
  "agents",
] as const;

// Google Cloud Blog (cloudblog.withgoogle.com/rss/) is a broad firmwide feed
// covering security, public-sector, threat-intel, storage, etc. For the
// knowledge lane we only want AI / data / developer engineering guidance, so
// require at least one of these terms (title scope, LL-081) and drop the rest.
const GCLOUD_RELEVANCE_KEYWORDS = [
  "ai",
  "ml",
  "machine learning",
  "gen ai",
  "generative",
  "gemini",
  "agent",
  "agents",
  "agentic",
  "antigravity",
  "llm",
  "model",
  "data",
  "analytics",
  "bigquery",
  "developer",
  "build",
  "open",
  "vertex",
  "rag",
  "embedding",
  "mlops",
  "kubernetes",
  "database",
  "coding",
  "software",
  "devops",
  "api",
  "serverless",
] as const;

// Hard noise for the knowledge lane: threat reports, sector/marketing posts,
// and routine roundups are not evergreen engineering knowledge (title scope).
const GCLOUD_EXCLUDE_KEYWORDS = [
  "threat",
  "apt",
  "espionage",
  "ransomware",
  "phishing",
  "cyberattack",
  "public sector",
  "government",
  "healthcare",
  "retail",
  "financial services",
  "what's new with google cloud",
  "weekly roundup",
  "startup forum",
  "partner",
  "sponsor",
] as const;

export const REGISTRY: Readonly<Record<string, SourceDefinition>> = Object.freeze({
  "anthropic-news": {
    id: "anthropic-news",
    displayName: "Anthropic News",
    category: "claude",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["anthropic", "claude"],
    feedUrl: "https://www.anthropic.com/news",
    tier: 1,
    collect: collectAnthropicNews,
  },
  "anthropic-engineering": {
    id: "anthropic-engineering",
    displayName: "Anthropic Engineering",
    category: "claude",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["anthropic", "engineering"],
    feedUrl: "https://www.anthropic.com/engineering",
    tier: 1,
    // Engineering deep-dives age slower than product announcements.
    halfLifeOverride: "architecture",
    // Best-practice / how-to knowledge: accumulate, never archive (R-022).
    evergreen: true,
    collect: collectAnthropicEngineering,
  },

  "openai-news": {
    id: "openai-news",
    displayName: "OpenAI News",
    category: "codex",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["openai"],
    feedUrl: "https://openai.com/news/rss.xml",
    tier: 1,
    collect: collectRss,
  },
  "openai-blog": {
    id: "openai-blog",
    displayName: "OpenAI Blog",
    category: "codex",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["openai"],
    feedUrl: "https://openai.com/blog/rss.xml",
    tier: 1,
    collect: collectRss,
  },
  "google-deepmind": {
    id: "google-deepmind",
    displayName: "Google DeepMind Blog",
    category: "gemini",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["google", "deepmind"],
    feedUrl: "https://deepmind.google/blog/rss.xml",
    tier: 1,
    collect: collectRss,
  },
  "google-developers": {
    id: "google-developers",
    displayName: "Google Developers Blog",
    category: "gemini",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["google"],
    feedUrl: "https://developers.googleblog.com/feeds/posts/default",
    tier: 1,
    // Feed lacks per-item <pubDate>; without this every item would inherit
    // collectedAt as publish date and surface as "today's update" (LL-045).
    fetchArticleDate: true,
    // Worker Free plan has a 50 external subrequest/invocation cap. This
    // source can otherwise spend 15+ extra article-page fetches in one batch.
    // Keep the entry slice aligned with the date-fetch cap so undated feed
    // items never fall through to normalize() as "collectedAt = publishedAt".
    maxArticleDateFetches: 4,
    maxEntriesPerRun: 4,
    collect: collectRss,
  },
  "github-blog-ai": {
    id: "github-blog-ai",
    displayName: "GitHub Blog (AI & ML)",
    category: "copilot",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["github"],
    // Canonical feed. /category/ai-and-ml/feed/ now 301-redirects here; using
    // the canonical URL avoids an extra redirect subrequest every run (LL-086).
    feedUrl: "https://github.blog/ai-and-ml/feed/",
    tier: 1,
    // Long-form technical explainers, not release announcements.
    halfLifeOverride: "architecture",
    // Best-practice / how-to knowledge: accumulate, never archive (R-022).
    evergreen: true,
    collect: collectRss,
  },
  "github-copilot": {
    id: "github-copilot",
    displayName: "GitHub Copilot Blog",
    category: "copilot",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["github", "copilot"],
    // Dedicated Copilot sub-feed: deeper coverage than the broad AI & ML feed
    // (e.g. "GitHub Copilot CLI combines model families"). Best-practice and
    // how-to posts about Copilot — accumulate as knowledge (R-022).
    feedUrl: "https://github.blog/ai-and-ml/github-copilot/feed/",
    tier: 1,
    halfLifeOverride: "architecture",
    evergreen: true,
    collect: collectRss,
  },
  "microsoft-foundry": {
    id: "microsoft-foundry",
    displayName: "Microsoft Foundry Blog",
    category: "copilot",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["microsoft", "foundry", "ai"],
    // Microsoft AI engineering knowledge: agent design/memory, toolboxes,
    // cost/quality guidance. The microsoft/ai-engineering-coach GitHub repo the
    // user cited has no releases and commit-tracking would be noise (LL-091),
    // so this official knowledge feed is the right capture point (LL-086).
    feedUrl: "https://devblogs.microsoft.com/foundry/feed/",
    tier: 1,
    halfLifeOverride: "architecture",
    // Best-practice / how-to knowledge: accumulate, never archive (R-022).
    evergreen: true,
    collect: collectRss,
  },
  "google-cloud-blog": {
    id: "google-cloud-blog",
    displayName: "Google Cloud Blog",
    category: "gemini",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["google", "cloud"],
    // Firmwide blog (cloudblog.withgoogle.com/rss/ is the real RSS; the
    // cloud.google.com/blog/rss SPA returns HTML, not items — LL-086). Broad,
    // so apply AI/data/dev relevance + threat/sector noise filters (R-017).
    feedUrl: "https://cloudblog.withgoogle.com/rss/",
    tier: 1,
    halfLifeOverride: "architecture",
    evergreen: true,
    keywordFilterScope: "title",
    includeKeywords: GCLOUD_RELEVANCE_KEYWORDS,
    excludeKeywords: GCLOUD_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "aws-ml-blog": {
    id: "aws-ml-blog",
    displayName: "AWS Machine Learning Blog",
    category: "agent-fw",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["aws", "ml", "bedrock"],
    // AWS ML/AI engineering knowledge: agent design, Bedrock, evaluation,
    // RAG/document pipelines. Practical best-practice content (R-022). Feed is
    // mostly AI/ML focused, but generic Amazon Quick / QuickSight BI product
    // operations and adjacent device announcements also appear. Require an
    // explicit AI/ML engineering signal before the Agent Frameworks lane.
    feedUrl: "https://aws.amazon.com/blogs/machine-learning/feed/",
    tier: 1,
    halfLifeOverride: "architecture",
    evergreen: true,
    keywordFilterScope: "title",
    includeKeywords: AWS_ML_RELEVANCE_KEYWORDS,
    excludeKeywords: AWS_ML_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "meta-engineering": {
    id: "meta-engineering",
    displayName: "Meta Engineering",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["meta", "engineering"],
    // Large-scale systems / ML infra deep-dives (retrieval, data ingestion,
    // reliability). Evergreen engineering knowledge (R-022).
    feedUrl: "https://engineering.fb.com/feed/",
    tier: 1,
    halfLifeOverride: "architecture",
    evergreen: true,
    maxEntriesPerRun: 6,
    collect: collectRss,
  },
  "netflix-techblog": {
    id: "netflix-techblog",
    displayName: "Netflix TechBlog",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["netflix", "engineering"],
    // Distributed-systems / data-platform engineering deep-dives. Medium feed
    // (medium.com/feed/netflix-techblog) is the real RSS; netflixtechblog.com
    // /feed returns HTML, not items (LL-086). Evergreen knowledge (R-022).
    feedUrl: "https://medium.com/feed/netflix-techblog",
    tier: 1,
    halfLifeOverride: "architecture",
    evergreen: true,
    maxEntriesPerRun: 6,
    collect: collectRss,
  },
  "github-changelog": {
    id: "github-changelog",
    displayName: "GitHub Changelog",
    category: "copilot",
    sourceType: "changelog",
    defaultLang: "en",
    autoTags: ["github", "changelog"],
    feedUrl: "https://github.blog/changelog/feed/",
    tier: 1,
    collect: collectRss,
  },
  "huggingface-blog": {
    id: "huggingface-blog",
    displayName: "Hugging Face Blog",
    category: "local-llm",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["huggingface", "open-model"],
    feedUrl: "https://huggingface.co/blog/feed.xml",
    tier: 1,
    collect: collectRss,
  },
  "ollama-releases": {
    id: "ollama-releases",
    displayName: "Ollama Releases",
    category: "local-llm",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["ollama", "release"],
    feedUrl: "https://github.com/ollama/ollama/releases.atom",
    tier: 1,
    collect: collectRss,
  },
  "arxiv-cs-cl": {
    id: "arxiv-cs-cl",
    displayName: "arXiv cs.CL",
    category: "research",
    sourceType: "paper",
    defaultLang: "en",
    autoTags: ["arxiv", "paper"],
    feedUrl: "https://rss.arxiv.org/rss/cs.CL",
    tier: 1,
    perSourceCap: 20,
    includeKeywords: RESEARCH_RELEVANCE_KEYWORDS,
    excludeKeywords: RESEARCH_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 12,
    collect: collectRss,
  },
  "arxiv-cs-se": {
    id: "arxiv-cs-se",
    displayName: "arXiv cs.SE",
    category: "research",
    sourceType: "paper",
    defaultLang: "en",
    autoTags: ["arxiv", "paper"],
    feedUrl: "https://rss.arxiv.org/rss/cs.SE",
    tier: 1,
    perSourceCap: 15,
    includeKeywords: RESEARCH_RELEVANCE_KEYWORDS,
    excludeKeywords: RESEARCH_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 12,
    collect: collectRss,
  },
  "zenn-ai": {
    id: "zenn-ai",
    displayName: "Zenn AI tag",
    category: "local-llm",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["zenn", "ai"],
    feedUrl: "https://zenn.dev/topics/ai/feed",
    tier: 1,
    perSourceCap: 30,
    includeKeywords: ZENN_AI_LOCAL_LLM_RELEVANCE_KEYWORDS,
    excludeKeywords: LOCAL_LLM_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 10,
    collect: collectRss,
  },
  "qiita-copilot": {
    id: "qiita-copilot",
    displayName: "Qiita GitHub Copilot tag",
    category: "copilot",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["qiita"],
    feedUrl: "https://qiita.com/tags/githubcopilot/feed.atom",
    tier: 1,
    collect: collectRss,
  },
  "zenn-llm": {
    id: "zenn-llm",
    displayName: "Zenn LLM tag",
    category: "local-llm",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["zenn", "llm"],
    feedUrl: "https://zenn.dev/topics/llm/feed",
    tier: 2,
    includeKeywords: LOCAL_LLM_RELEVANCE_KEYWORDS,
    excludeKeywords: LOCAL_LLM_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 10,
    collect: collectRss,
  },
  "zenn-claude": {
    id: "zenn-claude",
    displayName: "Zenn Claude tag",
    category: "claude",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["zenn", "claude"],
    feedUrl: "https://zenn.dev/topics/claude/feed",
    tier: 2,
    collect: collectRss,
  },
  "zenn-copilot": {
    id: "zenn-copilot",
    displayName: "Zenn GitHub Copilot tag",
    category: "copilot",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["zenn", "copilot"],
    feedUrl: "https://zenn.dev/topics/githubcopilot/feed",
    tier: 2,
    collect: collectRss,
  },
  "zenn-mcp": {
    id: "zenn-mcp",
    displayName: "Zenn MCP tag",
    category: "mcp",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["zenn", "mcp"],
    feedUrl: "https://zenn.dev/topics/mcp/feed",
    tier: 2,
    collect: collectRss,
  },
  "zenn-cursor": {
    id: "zenn-cursor",
    displayName: "Zenn Cursor tag",
    category: "cursor",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["zenn", "cursor"],
    feedUrl: "https://zenn.dev/topics/cursor/feed",
    tier: 2,
    collect: collectRss,
  },
  "qiita-claude": {
    id: "qiita-claude",
    displayName: "Qiita Claude tag",
    category: "claude",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["qiita", "claude"],
    feedUrl: "https://qiita.com/tags/claude/feed.atom",
    tier: 2,
    collect: collectRss,
  },
  "qiita-llm": {
    id: "qiita-llm",
    displayName: "Qiita LLM tag",
    category: "local-llm",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["qiita", "llm"],
    feedUrl: "https://qiita.com/tags/llm/feed.atom",
    tier: 2,
    includeKeywords: LOCAL_LLM_RELEVANCE_KEYWORDS,
    excludeKeywords: LOCAL_LLM_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 10,
    collect: collectRss,
  },
  "qiita-mcp": {
    id: "qiita-mcp",
    displayName: "Qiita MCP tag",
    category: "mcp",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["qiita", "mcp"],
    feedUrl: "https://qiita.com/tags/mcp/feed.atom",
    tier: 2,
    collect: collectRss,
  },
  "qiita-vscode": {
    id: "qiita-vscode",
    displayName: "Qiita VSCode tag",
    category: "vscode",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["qiita", "vscode"],
    feedUrl: "https://qiita.com/tags/vscode/feed.atom",
    tier: 2,
    includeKeywords: [
      "vscode",
      "vs code",
      "visual studio code",
      "vsコード",
      "devcontainer",
      "dev container",
      "extension",
      "拡張機能",
      "live share",
      "claude",
      "gemini",
      "antigravity",
      "copilot",
      "codex",
      "openai",
      "chatgpt",
      "ollama",
      "local llm",
      "ローカルllm",
      "gemma",
      "continue",
      "mcp",
      "cursor",
      "zed",
    ],
    excludeKeywords: ["makefile:2", "missing separator"],
    keywordFilterScope: "title",
    maxEntriesPerRun: 12,
    collect: collectRss,
  },
  "qiita-cursor": {
    id: "qiita-cursor",
    displayName: "Qiita Cursor tag",
    category: "cursor",
    sourceType: "blog",
    defaultLang: "ja",
    autoTags: ["qiita", "cursor"],
    feedUrl: "https://qiita.com/tags/cursor/feed.atom",
    tier: 2,
    collect: collectRss,
  },
  "vscode-updates": {
    id: "vscode-updates",
    displayName: "VS Code Updates",
    category: "vscode",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["vscode", "release"],
    feedUrl: "https://code.visualstudio.com/feed.xml",
    tier: 1,
    collect: collectVscodeUpdates,
  },
  "simonw-blog": {
    id: "simonw-blog",
    displayName: "Simon Willison's Weblog",
    category: "local-llm",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["newsletter", "llm"],
    feedUrl: "https://simonwillison.net/atom/everything/",
    tier: 2,
    includeKeywords: LOCAL_LLM_RELEVANCE_KEYWORDS,
    excludeKeywords: LOCAL_LLM_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 8,
    // Long-form essays referenced for years.
    halfLifeOverride: "architecture",
    collect: collectRss,
  },

  // ============ Tier 2 ============
  "aider-releases": {
    id: "aider-releases",
    displayName: "Aider Releases",
    category: "aider",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["aider", "release"],
    feedUrl: "https://github.com/Aider-AI/aider/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "cline-releases": {
    id: "cline-releases",
    displayName: "Cline Releases",
    category: "cline",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["cline", "release"],
    feedUrl: "https://github.com/cline/cline/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "continue-releases": {
    id: "continue-releases",
    displayName: "Continue.dev Releases",
    category: "copilot",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["continue", "release"],
    feedUrl: "https://github.com/continuedev/continue/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "openhands-releases": {
    id: "openhands-releases",
    displayName: "OpenHands Releases",
    category: "opencode",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["openhands", "release"],
    feedUrl: "https://github.com/All-Hands-AI/OpenHands/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "zed-releases": {
    id: "zed-releases",
    displayName: "Zed Editor Releases",
    category: "cursor",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["zed", "editor", "release"],
    feedUrl: "https://github.com/zed-industries/zed/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "autogen-releases": {
    id: "autogen-releases",
    displayName: "Microsoft AutoGen Releases",
    category: "agent-fw",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["autogen", "agent", "release"],
    feedUrl: "https://github.com/microsoft/autogen/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "langchain-releases": {
    id: "langchain-releases",
    displayName: "LangChain Releases",
    category: "agent-fw",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["langchain", "agent", "release"],
    feedUrl: "https://github.com/langchain-ai/langchain/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "semantic-kernel-releases": {
    id: "semantic-kernel-releases",
    displayName: "Semantic Kernel Releases",
    category: "agent-fw",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["semantic-kernel", "agent", "release"],
    feedUrl: "https://github.com/microsoft/semantic-kernel/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "mcp-servers-releases": {
    id: "mcp-servers-releases",
    displayName: "MCP Servers Releases",
    category: "mcp",
    sourceType: "release",
    defaultLang: "en",
    autoTags: ["mcp", "release"],
    feedUrl: "https://github.com/modelcontextprotocol/servers/releases.atom",
    tier: 2,
    collect: collectRss,
  },
  "cursor-changelog": {
    id: "cursor-changelog",
    displayName: "Cursor Changelog",
    category: "cursor",
    sourceType: "changelog",
    defaultLang: "en",
    autoTags: ["cursor", "changelog"],
    feedUrl: "https://www.cursor.com/changelog/rss.xml",
    tier: 2,
    collect: collectRss,
  },
  "arxiv-cs-ai": {
    id: "arxiv-cs-ai",
    displayName: "arXiv cs.AI",
    category: "research",
    sourceType: "paper",
    defaultLang: "en",
    autoTags: ["arxiv", "paper"],
    feedUrl: "https://rss.arxiv.org/rss/cs.AI",
    tier: 2,
    perSourceCap: 25,
    includeKeywords: RESEARCH_RELEVANCE_KEYWORDS,
    excludeKeywords: RESEARCH_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 12,
    collect: collectRss,
  },
  "arxiv-cs-lg": {
    id: "arxiv-cs-lg",
    displayName: "arXiv cs.LG",
    category: "research",
    sourceType: "paper",
    defaultLang: "en",
    autoTags: ["arxiv", "paper"],
    feedUrl: "https://rss.arxiv.org/rss/cs.LG",
    tier: 2,
    perSourceCap: 20,
    includeKeywords: RESEARCH_RELEVANCE_KEYWORDS,
    excludeKeywords: RESEARCH_EXCLUDE_KEYWORDS,
    maxEntriesPerRun: 12,
    collect: collectRss,
  },

  // ============ Tech News (Tier 2) ============
  "apple-newsroom": {
    id: "apple-newsroom",
    displayName: "Apple Newsroom",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["apple", "news"],
    feedUrl: "https://www.apple.com/newsroom/rss-feed.rss",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "microsoft-source": {
    id: "microsoft-source",
    displayName: "Microsoft Source",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["microsoft", "news"],
    feedUrl: "https://news.microsoft.com/source/feed/",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "google-keyword": {
    id: "google-keyword",
    displayName: "Google Keyword Blog",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["google", "news"],
    feedUrl: "https://blog.google/rss/",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "meta-newsroom": {
    id: "meta-newsroom",
    displayName: "Meta Newsroom",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["meta", "news"],
    feedUrl: "https://about.fb.com/news/feed/",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "aws-news": {
    id: "aws-news",
    displayName: "AWS News Blog",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["aws", "amazon", "news"],
    feedUrl: "https://aws.amazon.com/blogs/aws/feed/",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "nvidia-blog": {
    id: "nvidia-blog",
    displayName: "NVIDIA Blog",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["nvidia", "news"],
    feedUrl: "https://blogs.nvidia.com/feed/",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "techcrunch": {
    id: "techcrunch",
    displayName: "TechCrunch",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["techcrunch", "news"],
    feedUrl: "https://techcrunch.com/feed/",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "the-verge": {
    id: "the-verge",
    displayName: "The Verge",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["verge", "news"],
    feedUrl: "https://www.theverge.com/rss/index.xml",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  "ars-technica": {
    id: "ars-technica",
    displayName: "Ars Technica",
    category: "tech-news",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["ars-technica", "news"],
    feedUrl: "https://arstechnica.com/feed/",
    tier: 2,
    includeKeywords: TECH_NEWS_RELEVANCE_KEYWORDS,
    excludeKeywords: TECH_NEWS_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectRss,
  },
  // ============ Tier 3 ============
  "dora-insights": {
    id: "dora-insights",
    displayName: "DORA Insights (Google)",
    category: "research",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["dora", "devops", "research"],
    feedUrl: "https://dora.dev/insights/index.xml",
    tier: 2,
    // DORA reports are cited for years.
    halfLifeOverride: "architecture",
    collect: collectRss,
    excludeKeywords: DORA_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
  },
  "hn-ai": {
    id: "hn-ai",
    displayName: "Hacker News — AI coding",
    category: "tech-news",
    sourceType: "community",
    defaultLang: "en",
    autoTags: ["hackernews", "community"],
    feedUrl:
      "https://hn.algolia.com/api/v1/search?query=%22AI+coding%22+OR+%22LLM%22+OR+%22MCP%22&tags=story&hitsPerPage=30",
    tier: 3,
    includeKeywords: HN_AI_RELEVANCE_KEYWORDS,
    excludeKeywords: HN_AI_EXCLUDE_KEYWORDS,
    keywordFilterScope: "title",
    maxEntriesPerRun: 8,
    collect: collectHnAlgolia,
  },
  "user-opml": {
    id: "user-opml",
    displayName: "User OPML (custom feeds)",
    category: "research",
    sourceType: "blog",
    defaultLang: "en",
    autoTags: ["user"],
    feedUrl: "file://data/user-opml.xml",
    tier: 3,
    collect: collectOpml,
  },
  // Example YouTube channel — Anthropic. Users can copy this pattern.
  "youtube-anthropic": {
    ...youtubeChannel(
      "youtube-anthropic",
      "YouTube — Anthropic",
      "UCrDwWp7EBBv4NwvScIpBDOA",
      ["anthropic"],
    ),
    category: "claude",
  },
});

export function listSources(): SourceDefinition[] {
  return Object.values(REGISTRY);
}
